version: '3'

services:
  app:
    build: .
    ports:
      - "12001:12001"
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped